# Trendyol Data Science Bootcamp Capstone Project

Importing libraries

In [1]:
import numpy as np
import pandas as pd
from tqdm import trange

Reading Datasets to Dataframes

In [2]:
df_cust = pd.read_csv("/Users/osmanbahtiyar/Downloads/customers.csv.gz", compression="gzip")

In [3]:
df_cust

customer_id club_member_status  \
0        00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...             ACTIVE   
1        0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...             ACTIVE   
2        000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...             ACTIVE   
3        00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...             ACTIVE   
4        00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...             ACTIVE   
...                                                    ...                ...   
1371975  ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...             ACTIVE   
1371976  ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab5...             ACTIVE   
1371977  ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1...             ACTIVE   
1371978  ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...             ACTIVE   
1371979  ffffd9ac14e89946416d80e791d064701994755c3ab686...         PRE-CREATE   

        fashion_news_frequency   age  
0                         NONE  49.0  
1                         NONE  25.0  
2                         NONE  24.0  
3                         NONE  54.0  
4                    Regularly  52.0  
...                        ...   ...  
1371975                   NONE  24.0  
1371976                   NONE  21.0  
1371977              Regularly  21.0  
1371978              Regularly  18.0  
1371979                   NONE  65.0  

[1371980 rows x 4 columns]

In [4]:
df_artic = pd.read_csv("/Users/osmanbahtiyar/Downloads/articles.csv.gz", compression="gzip")

In [5]:
df_artic

article_id  product_code               prod_name  product_type_no  \
0        108775015        108775               Strap top              253   
1        108775044        108775               Strap top              253   
2        108775051        108775           Strap top (1)              253   
3        110065001        110065       OP T-shirt (Idro)              306   
4        110065002        110065       OP T-shirt (Idro)              306   
...            ...           ...                     ...              ...   
105537   953450001        953450  5pk regular Placement1              302   
105538   953763001        953763       SPORT Malaga tank              253   
105539   956217002        956217         Cartwheel dress              265   
105540   957375001        957375        CLAIRE HAIR CLAW               72   
105541   959461001        959461            Lounge dress              265   

       product_type_name  product_group_name  graphical_appearance_no  \
0               Vest top  Garment Upper body                  1010016   
1               Vest top  Garment Upper body                  1010016   
2               Vest top  Garment Upper body                  1010017   
3                    Bra           Underwear                  1010016   
4                    Bra           Underwear                  1010016   
...                  ...                 ...                      ...   
105537             Socks      Socks & Tights                  1010014   
105538          Vest top  Garment Upper body                  1010016   
105539             Dress   Garment Full body                  1010016   
105540         Hair clip         Accessories                  1010016   
105541             Dress   Garment Full body                  1010016   

       graphical_appearance_name  colour_group_code colour_group_name  ...  \
0                          Solid                  9             Black  ...   
1                          Solid                 10             White  ...   
2                         Stripe                 11         Off White  ...   
3                          Solid                  9             Black  ...   
4                          Solid                 10             White  ...   
...                          ...                ...               ...  ...   
105537           Placement print                  9             Black  ...   
105538                     Solid                  9             Black  ...   
105539                     Solid                  9             Black  ...   
105540                     Solid                  9             Black  ...   
105541                     Solid                 11         Off White  ...   

          department_name index_code        index_name index_group_no  \
0            Jersey Basic          A        Ladieswear              1   
1            Jersey Basic          A        Ladieswear              1   
2            Jersey Basic          A        Ladieswear              1   
3          Clean Lingerie          B  Lingeries/Tights              1   
4          Clean Lingerie          B  Lingeries/Tights              1   
...                   ...        ...               ...            ...   
105537          Socks Bin          F          Menswear              3   
105538             Jersey          A        Ladieswear              1   
105539             Jersey          A        Ladieswear              1   
105540  Small Accessories          D           Divided              2   
105541             Jersey          A        Ladieswear              1   

        index_group_name section_no            section_name garment_group_no  \
0             Ladieswear         16  Womens Everyday Basics             1002   
1             Ladieswear         16  Womens Everyday Basics             1002   
2             Ladieswear         16  Womens Everyday Basics             1002   
3             Ladieswear         61         Womens Lingerie             

In [6]:
df_trans = pd.read_csv("/Users/osmanbahtiyar/Downloads/transactions.csv.gz", compression="gzip")

In [8]:
df_trans

t_dat                                        customer_id  \
0         2018-09-20  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   
1         2018-09-20  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   
2         2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   
3         2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   
4         2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   
...              ...                                                ...   
31788319  2020-09-22  fff2282977442e327b45d8c89afde25617d00124d0f999...   
31788320  2020-09-22  fff2282977442e327b45d8c89afde25617d00124d0f999...   
31788321  2020-09-22  fff380805474b287b05cb2a7507b9a013482f7dd0bce0e...   
31788322  2020-09-22  fff4d3a8b1f3b60af93e78c30a7cb4cf75edaf2590d3e5...   
31788323  2020-09-22  fffef3b6b73545df065b521e19f64bf6fe93bfd450ab20...   

          article_id     price  sales_channel_id  
0          663713001  0.050831                 2  
1          541518023  0.030492                 2  
2          505221004  0.015237                 2  
3          685687003  0.016932                 2  
4          685687004  0.016932                 2  
...              ...       ...               ...  
31788319   929511001  0.059305                 2  
31788320   891322004  0.042356                 2  
31788321   918325001  0.043203                 1  
31788322   833459002  0.006763                 1  
31788323   898573003  0.033881                 2  

[31788324 rows x 5 columns]

Creating article_id_new and customer_id_new columns. I want to use new ids as a index for matrix factorization.

In [9]:
article_ids = df_trans['article_id']
uniques = article_ids.unique()
length = len(uniques)
arr = np.array(list(range(length)))
dict1 = {uniques[i]:i for i in range(length)}
df_trans['article_id_new'] = df_trans['article_id'].apply(lambda x : dict1[x])
df_trans['article_id_new']

0                0
1                1
2                2
3                3
4                4
             ...  
31788319    102734
31788320     97490
31788321    104185
31788322     70100
31788323    102985
Name: article_id_new, Length: 31788324, dtype: int64

In [10]:
customer_ids = df_trans['customer_id']
unique_customers = customer_ids.unique()
len_cus_uniq = len(unique_customers)
arr_cus = np.array(list(range(len_cus_uniq)))
dict2 = {unique_customers[i]:i for i in range(len_cus_uniq)}
df_trans['customer_id_new'] = df_trans['customer_id'].apply(lambda x : dict2[x])
df_trans['customer_id_new']

0                 0
1                 0
2                 1
3                 1
4                 1
             ...   
31788319     212537
31788320     212537
31788321    1090369
31788322     729233
31788323    1025409
Name: customer_id_new, Length: 31788324, dtype: int64

In [12]:
df_trans

t_dat                                        customer_id  \
0         2018-09-20  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   
1         2018-09-20  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   
2         2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   
3         2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   
4         2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   
...              ...                                                ...   
31788319  2020-09-22  fff2282977442e327b45d8c89afde25617d00124d0f999...   
31788320  2020-09-22  fff2282977442e327b45d8c89afde25617d00124d0f999...   
31788321  2020-09-22  fff380805474b287b05cb2a7507b9a013482f7dd0bce0e...   
31788322  2020-09-22  fff4d3a8b1f3b60af93e78c30a7cb4cf75edaf2590d3e5...   
31788323  2020-09-22  fffef3b6b73545df065b521e19f64bf6fe93bfd450ab20...   

          article_id     price  sales_channel_id  article_id_new  \
0          663713001  0.050831                 2               0   
1          541518023  0.030492                 2               1   
2          505221004  0.015237                 2               2   
3          685687003  0.016932                 2               3   
4          685687004  0.016932                 2               4   
...              ...       ...               ...             ...   
31788319   929511001  0.059305                 2          102734   
31788320   891322004  0.042356                 2           97490   
31788321   918325001  0.043203                 1          104185   
31788322   833459002  0.006763                 1           70100   
31788323   898573003  0.033881                 2          102985   

          customer_id_new  
0                       0  
1                       0  
2                       1  
3                       1  
4                       1  
...                   ...  
31788319           212537  
31788320           212537  
31788321          1090369  
31788322           729233  
31788323          1025409  

[31788324 rows x 7 columns]

I splited the data to three parts. These are train, validation and test sets. I used last week as test set, the week before last week as validation set and the remaining part as train set. Then I used the validation set to optimize my hyperparameters. My validation set just contains one week before last week so my hyperparameters can maximize the last week.

In [15]:
validation_split_idx = int(df_trans.shape[0]*0.98)
test_split_idx = int(df_trans.shape[0]*0.99)

In [16]:
df_train = df_trans.loc[0:validation_split_idx]
df_val = df_trans.loc[validation_split_idx : test_split_idx] 
df_test = df_trans.loc[test_split_idx:]

In [17]:
df_train

t_dat                                        customer_id  \
0         2018-09-20  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   
1         2018-09-20  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   
2         2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   
3         2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   
4         2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   
...              ...                                                ...   
31152553  2020-09-05  4499cb5dd11de1dbb5d5c9ed323714c335efd1eb9d4c57...   
31152554  2020-09-05  4499cb5dd11de1dbb5d5c9ed323714c335efd1eb9d4c57...   
31152555  2020-09-05  4499cb5dd11de1dbb5d5c9ed323714c335efd1eb9d4c57...   
31152556  2020-09-05  449cea12e175cc607c95d48c622b6139af43d243dec493...   
31152557  2020-09-05  449cea12e175cc607c95d48c622b6139af43d243dec493...   

          article_id     price  sales_channel_id  article_id_new  \
0          663713001  0.050831                 2               0   
1          541518023  0.030492                 2               1   
2          505221004  0.015237                 2               2   
3          685687003  0.016932                 2               3   
4          685687004  0.016932                 2               4   
...              ...       ...               ...             ...   
31152553   568601023  0.050831                 1           36759   
31152554   652730004  0.050831                 1           39564   
31152555   686564013  0.033881                 1           60922   
31152556   706016019  0.033881                 1           66265   
31152557   516000090  0.016932                 1           67828   

          customer_id_new  
0                       0  
1                       0  
2                       1  
3                       1  
4                       1  
...                   ...  
31152553           648670  
31152554           648670  
31152555           648670  
31152556           109638  
31152557           109638  

[31152558 rows x 7 columns]

In [76]:
user_unique = df_trans['customer_id'].nunique()
item_unique = df_trans['article_id'].nunique()
print(user_unique)
print(item_unique)

1362281
104547


While creating the R matrix, I decided to make an explicit matrix. I used the amount of times a user bought product as rating. 

In [20]:
df_train_new = df_train.groupby(['customer_id_new', 'article_id_new']).size()
df_val_new = df_val.groupby(['customer_id_new', 'article_id_new']).size()
df_test_new = df_test.groupby(['customer_id_new', 'article_id_new']).size()

In [21]:
df_train_new

customer_id_new  article_id_new
0                0                 2
                 1                 1
                 1702              1
                 2880              2
                 39611             1
                                  ..
1348225          95726             1
                 99938             1
1348226          78905             1
                 99537             1
                 101549            1
Length: 26760915, dtype: int64

In [22]:
df_train_new.shape

(26760915,)

Training and Hyperparameter Optimization for d and lambda. 
Data is very large so I can't create R matrix because of memory issues. I solved this problem with just using indexes to do gradient descent.

In [23]:
total_val_e = 0
best_total_e = float('inf')
best_lamb = 0.1
best_d = 10
alpha = 0.0001   # Learning rate

lambs = [0.001,0.01,0.1]
d_list = [10,100,1000]

for lamb in lambs:
    for d_ in d_list:

        U = np.random.rand(user_unique,d_)
        V = np.random.rand(d_,item_unique)

        with trange(20) as epochs:
            for _ in epochs:
                total_e = 0   
                for k,sample in enumerate(df_train_new.iteritems()):
                    i = sample[0][0]
                    j = sample[0][1]

                    y_pred = np.dot(U[i, :], V[:, j])
                    e = sample[1] - y_pred

                    U[i, :] += (2 * e * V[:, j] - 2 * lamb * U[i, :]) * alpha
                    V[:, j] += (2 * e * U[i, :] - 2 * lamb * V[:, j]) * alpha

                    total_e += e ** 2

                epochs.set_description(f'Total Square Error: {total_e:.2f}')
                print(total_e)
        
        total_val_e = 0
        for k,sample in enumerate(df_val_new.iteritems()):
            i = sample[0][0]
            j = sample[0][1]

            y_pred = np.dot(U[i, :], V[:, j])
            e = np.abs(sample[1] - y_pred)

            total_val_e += e

        print(total_val_e)
        if total_val_e < best_total_e:
            best_d = d_
            best_lamb = lamb
            best_U = U
            best_V = V
            best_total_e = total_val_e

print(best_d, best_lamb, best_U, best_V)

Total Square Error: 46270457.07:  33%|███▋       | 1/3 [09:09<18:18, 549.12s/it]

46270457.067279406


Total Square Error: 29079965.73:  67%|███████▎   | 2/3 [18:08<09:03, 543.16s/it]

29079965.73418979


Total Square Error: 22965952.51: 100%|███████████| 3/3 [27:09<00:00, 543.08s/it]


22965952.509606306
242470.31046498113


Total Square Error: 45375370.33:  33%|███▋       | 1/3 [08:59<17:59, 539.59s/it]

45375370.32837057


Total Square Error: 27968132.18:  67%|███████▎   | 2/3 [18:01<09:01, 541.08s/it]

27968132.175512455


Total Square Error: 21990917.93: 100%|███████████| 3/3 [27:09<00:00, 543.01s/it]


21990917.926134527
235443.6244738167
10 0.1 [[0.20396461 0.17568702 0.42301719 ... 0.19009866 0.91354062 0.8828529 ]
 [0.57137166 0.28423562 0.07472114 ... 0.19505368 0.34647486 0.27380938]
 [0.0313316  0.72159074 0.43816743 ... 0.3557925  0.94137001 0.07307757]
 ...
 [0.72428833 0.97263695 0.45554179 ... 0.20092801 0.27549356 0.50740218]
 [0.14807775 0.37760275 0.87009213 ... 0.66032447 0.42379585 0.48375176]
 [0.79313478 0.75828502 0.30484134 ... 0.66366797 0.98605883 0.04064531]] [[0.31555886 0.30658724 0.72125022 ... 0.42497731 0.93703406 0.30475969]
 [0.37433591 0.36223957 0.74495402 ... 0.47752436 0.54870056 0.30291768]
 [0.02581784 0.51223943 0.03651858 ... 0.02711351 0.9693277  0.50967896]
 ...
 [0.17838714 0.42953046 0.2091167  ... 0.22581368 0.96901737 0.99444747]
 [0.35152377 0.64435652 0.49694162 ... 0.51621341 0.19174183 0.68940598]
 [0.2716586  0.35409118 0.13982245 ... 0.27222913 0.15833173 0.42178945]]


In [27]:
best_d

10

In [28]:
best_lamb

0.1

MAE for test set

In [43]:
total_test_e = 0

for k,sample in enumerate(df_test_new.iteritems()):
    i = sample[0][0]
    j = sample[0][1]

    y_pred = np.dot(best_U[i, :], best_V[:, j])
    y_pred_rounded = round(y_pred)
    e = np.abs(sample[1] - y_pred_rounded)

    total_test_e += e
    
print(total_test_e)

239814


In [38]:
df_test_new

customer_id_new  article_id_new
0                100206            1
3                100494            1
6                98365             1
33               1408              2
46               99220             1
                                  ..
1362278          104514            1
1362279          99158             2
1362280          68956             1
                 102215            1
                 102661            1
Length: 281578, dtype: int64

In [45]:
user_unique

1362281

In [58]:
item_unique

104547

Creating top 5 article recommendations for users

In [70]:
recommendations = []
for i in range(user_unique):
    max_five = []    
    y_pred = np.dot(best_U[i, :], best_V[:])
    
    for k in range(5):
        max_v = y_pred.max()
        max_idx = y_pred.argmax()
        max_five.append((max_v,max_idx))
        y_pred[max_idx] = -1
    
    recommendations.append(max_five)
    if i % 1000 == 0:       
        print("user is done: ", i, "/", user_unique)

user is done:  0 / 1362281
user is done:  1000 / 1362281
user is done:  2000 / 1362281
user is done:  3000 / 1362281
user is done:  4000 / 1362281
user is done:  5000 / 1362281
user is done:  6000 / 1362281
user is done:  7000 / 1362281
user is done:  8000 / 1362281
user is done:  9000 / 1362281
user is done:  10000 / 1362281
user is done:  11000 / 1362281
user is done:  12000 / 1362281
user is done:  13000 / 1362281
user is done:  14000 / 1362281
user is done:  15000 / 1362281
user is done:  16000 / 1362281
user is done:  17000 / 1362281
user is done:  18000 / 1362281
user is done:  19000 / 1362281
user is done:  20000 / 1362281
user is done:  21000 / 1362281
user is done:  22000 / 1362281
user is done:  23000 / 1362281
user is done:  24000 / 1362281
user is done:  25000 / 1362281
user is done:  26000 / 1362281
user is done:  27000 / 1362281
user is done:  28000 / 1362281
user is done:  29000 / 1362281
user is done:  30000 / 1362281
user is done:  31000 / 1362281
user is done:  32000 

In [75]:
recommendations

[[(4.971525691427256, 35781),
  (4.80733152339167, 30881),
  (4.797133593015322, 100108),
  (4.746297086784331, 100379),
  (4.73129118895146, 18547)],
 [(4.1400737477035126, 100379),
  (4.08455339859392, 18547),
  (4.015029431352501, 76914),
  (3.982594504807187, 35781),
  (3.9543563810557147, 36620)],
 [(4.948983559132876, 39002),
  (4.878065359494544, 35781),
  (4.86799333471264, 18547),
  (4.826111791431273, 7689),
  (4.750035791506444, 70582)],
 [(4.52160080379905, 30881),
  (4.47345541628434, 35781),
  (4.371642981887312, 42598),
  (4.356775755440212, 32016),
  (4.337363922047151, 18547)],
 [(4.474755444163396, 35781),
  (4.441175639303665, 59370),
  (4.437648965029179, 47357),
  (4.316372974777745, 65437),
  (4.306281584586966, 29471)],
 [(4.559285133518416, 65437),
  (4.552828032661399, 4235),
  (4.549551955229687, 85825),
  (4.534388207531658, 31134),
  (4.531577978693744, 61308)],
 [(3.715491658369332, 35781),
  (3.7116931459027622, 101947),
  (3.690134506514288, 100108),
  (3